name: LimitHeight
main: LimitHeight\Main
version: "1.1"
api: [1.11.0]
load: STARTUP
author: EvolSoft
description: Limit the build height
website: http://www.evolsoft.tk

permissions:
 limitheight:
  default: op
  description: LimitHeight permissions.
  children:
    limitheight.bypass:
      default: op
      description: Allows players to bypass the height limit
